# Generated by Django 5.1.6 on 2025-04-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinavKullanicisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=50, unique=True)),
                ('sifre', models.CharField(max_length=50)),
                ('sinava_girdi_mi', models.BooleanField(default=False)),
            ],
        ),
    ]
