# Generated by Django 5.1.6 on 2025-04-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0002_sinavkullanicisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(default='Güvenlik Sınavı', max_length=100)),
                ('sure', models.IntegerField(help_text='Sınav süresi (dakika cinsinden)')),
            ],
        ),
    ]
