# Generated by Django 5.1.6 on 2025-04-25 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0003_sinav'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinavSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogru_sayisi', models.IntegerField()),
                ('yanlis_sayisi', models.IntegerField()),
                ('puan', models.IntegerField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinav.sinavkullanicisi')),
            ],
        ),
    ]
