# Generated by Django 5.1.6 on 2025-04-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0004_sinavsonucu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinav',
            name='baslik',
        ),
        migrations.AddField(
            model_name='sinav',
            name='isim',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='sure',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
