# Generated by Django 5.1.6 on 2025-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav', '0005_remove_sinav_baslik_sinav_isim_alter_sinav_sure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinav',
            name='isim',
        ),
        migrations.AddField(
            model_name='sinav',
            name='baslik',
            field=models.CharField(default='Güvenlik Sınavı', max_length=100),
        ),
        migrations.AlterField(
            model_name='sinav',
            name='sure',
            field=models.IntegerField(help_text='Sınav süresi (dakika cinsinden)'),
        ),
    ]
